version: '3'

services:
  redis-master:
    image: redis
    restart: always
    container_name: redis-master
    ports:
      - 6379:6379
    volumes:
      - ./data/6379:/data
    command: [
      '--appendonly ${REDIS_APPENDONLY}'
    ]

  redis-replica-1:
    image: redis
    depends_on:
      - redis-master
    restart: always
    container_name: redis-replica-1
    ports:
      - 6380:6379
    volumes:
      - ./data/6380:/data
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--replicaof redis-master 6379',
      # REPLICA DOCKER/NAT
      '--replica-announce-ip ${HOST_IP}',
      '--replica-announce-port 6380'
    ]

  redis-replica-2:
    image: redis
    depends_on:
      - redis-master
    restart: always
    container_name: redis-replica-2
    ports:
      - 6381:6379
    volumes:
      - ./data/6381:/data
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--replicaof redis-master 6379',
      # REPLICA DOCKER/NAT
      '--replica-announce-ip ${HOST_IP}',
      '--replica-announce-port 6381'
    ]

  redis-sentinel-1:
    build: .
    image: redis-sentinel
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: always
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: [
      # mymaster
      '--sentinel monitor mymaster redis-master 6379 2',
      '--sentinel down-after-milliseconds mymaster 30000',
      '--sentinel parallel-syncs mymaster 1',
      '--sentinel failover-timeout mymaster 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26379'
    ]

  redis-sentinel-2:
    build: .
    image: redis-sentinel
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: always
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    command: [
      # mymaster
      '--sentinel monitor mymaster redis-master 6379 2',
      '--sentinel down-after-milliseconds mymaster 30000',
      '--sentinel parallel-syncs mymaster 1',
      '--sentinel failover-timeout mymaster 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26380'
    ]

  redis-sentinel-3:
    build: .
    image: redis-sentinel
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    restart: always
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: [
      # mymaster
      '--sentinel monitor mymaster redis-master 6379 2',
      '--sentinel down-after-milliseconds mymaster 30000',
      '--sentinel parallel-syncs mymaster 1',
      '--sentinel failover-timeout mymaster 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26381'
    ]