version: '3'

services:
  redis-sentinel-1:
    build: .
    image: redis-sentinel
    restart: always
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: [
      # SENTINEL
      '--sentinel monitor ${SENTINEL_MASTER_NAME} ${HOST_IP} 6379 2',
      '--sentinel down-after-milliseconds ${SENTINEL_MASTER_NAME} 30000',
      '--sentinel parallel-syncs ${SENTINEL_MASTER_NAME} 1',
      '--sentinel failover-timeout ${SENTINEL_MASTER_NAME} 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26379'
    ]

  redis-sentinel-2:
    image: redis-sentinel
    restart: always
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    command: [
      # SENTINEL
      '--sentinel monitor ${SENTINEL_MASTER_NAME} ${HOST_IP} 6379 2',
      '--sentinel down-after-milliseconds ${SENTINEL_MASTER_NAME} 30000',
      '--sentinel parallel-syncs ${SENTINEL_MASTER_NAME} 1',
      '--sentinel failover-timeout ${SENTINEL_MASTER_NAME} 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26380'
    ]

  redis-sentinel-3:
    image: redis-sentinel
    restart: always
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: [
      # SENTINEL
      '--sentinel monitor ${SENTINEL_MASTER_NAME} ${HOST_IP} 6379 2',
      '--sentinel down-after-milliseconds ${SENTINEL_MASTER_NAME} 30000',
      '--sentinel parallel-syncs ${SENTINEL_MASTER_NAME} 1',
      '--sentinel failover-timeout ${SENTINEL_MASTER_NAME} 180000',
      # SENTINEL DOCKER/NAT
      '--sentinel announce-ip ${HOST_IP}',
      '--sentinel announce-port 26381'
    ]